### ISSUE TITLE
Replace Java libraries with kotlin ones

### ISSUE THREAD

**Issue by michaelbukachi** [droidconKE/droidconKE#10]
In the spirit of kotlin, we should try to replace all libs with kotlin versions if they exist.
So:  
rxJava -> coroutines
butterknife -> kotlin extensions
java files -> kotlin ones

**Comment by wangerekaharun** [comment]
Yeah i agree with you, there is a kotlin branch with the above changes planned to be done.

**Comment by mayeedwin** [comment]
Actually the Kotlin codebase is already available if this is a clone from the[ io18 schedule app](https://github.com/google/iosched)

**Comment by michaelbukachi** [comment]
I was told it was a clone of io2016. Is that correct?

**Comment by mayeedwin** [comment]
> Actually the Kotlin codebase is already available if this is a clone from the[ io18 schedule app](https://github.com/google/iosched)

I would prefer they use the 2018 one here

**Comment by wangerekaharun** [comment]
Updated the Kotlin Branch with the current features that are in the master branch whose codebase is java . @michaelbukachi checkout our [Contributions Guidelines](https://github.com/droidconKE/droidconKE/blob/master/CONTRIBUTING.md).

**Comment by michaelbukachi** [comment]
I noticed the develop branch is in Java. I wanted to make kotlin contributions. How do I proceed?

**Comment by wangerekaharun** [comment]
Use the kotlin branch for this case
