### ISSUE TITLE
Integrate firebase ktx

### ISSUE THREAD

**Issue by michaelbukachi** [droidconKE/droidconKE#22]
In the interest of [this](https://dev.to/rosariopfernandes/using-kotlin-extension-functions-and-coroutines-with-firebase-j0k) article, I propose we integrate **firebase-ktx** with immediate effect into the kotlin branch :joy:.

**Comment by wangerekaharun** [comment]
In support of that. You can feel free to integrate

**Comment by wangerekaharun** [comment]
Let me work on it asap

**Comment by wangerekaharun** [comment]
Completed the intergration
