### ISSUE TITLE
MVVM Review

### ISSUE THREAD

**Issue by wangerekaharun** [droidconKE/droidconKE#3]
Review MVVM codebase Structure

**Comment by jumaallan** [comment]
@wangerekaharun I feel this would be a big review for the project, just organising the project packages using the MVVM Architecture guidelines. I was going through the codebase and will create a few pull requests also 👍

**Comment by wangerekaharun** [comment]
@jumaallan We are already using MVVM guidelines in the project,just review the MVVM structure that we have used and recommend on changes and improvements that we can make

**Comment by jumaallan** [comment]
@wangerekaharun More like grouping the related packages into main ones, I will create a simple pull request with what am trying to explain. I saw you are using the MVVM way, but my idea was to kinda group a few packages together to achieve a nice project structure.

**Comment by wangerekaharun** [comment]
@jumaallan I get what you are saying. When done just do a PR and we will review then merge the changes. Also any other recommendation would be nice before we roll out the first version of the app

**Comment by jumaallan** [comment]
@wangerekaharun Great. Will look at it bro
