### ISSUE TITLE
Minimum SDK Version

### ISSUE THREAD

**Issue by etonotieno** [droidconKE/droidconKE#4]
If possible can you add support for API level 19 and above to target more users. The current version might limit many future users of the app.

**Comment by wangerekaharun** [comment]
We set the minimum to API 21 due to libraries which are not backward compatible but we shall test the app for devices below 21 but above 19 then decide with the results in mind.

**Comment by etonotieno** [comment]
I have a suggestion. What if you use the AndroidX libraries instead of the v28 libraries. You can get backwards compatability and at the same time new API features. You can use the new Material Design Components  library to get new widgets like Chips while at the same time supporting older devices.

**Comment by wangerekaharun** [comment]
Android X libraries are still in beta version and more unstable as compared to the alpha version of design support library version 28. So we are still testing on the devices below api 21 with the alpha version of design support libraries v28 alpha
