### ISSUE TITLE
Cannot go through with signin

### ISSUE THREAD

**Issue by nathanmkaya** [droidconKE/droidconKE#8]
I have tried building and running the app but the signin process fails with com.google.android.gms.common.api.ApiException: 16.
I have tried to figure out the issue and this is what I came up with https://stackoverflow.com/questions/52407793/com-google-android-gms-common-api-apiexception-16

Please advice...

**Comment by wangerekaharun** [comment]
I have to add your SHA1 key to firebase for it to accept  the google sign
in option

**Comment by michaelbukachi** [comment]
I also can't sign in. How do we provide our SHA 1 keys ?

**Comment by wangerekaharun** [comment]
Share your SHA1 Keys via this email [harunwangereka@gmail.com](harunwangereka@gmail.com)

**Comment by wangerekaharun** [comment]
Added Firebase Setup steps [here](https://github.com/droidconKE/droidconKE/blob/master/FIREBASE.md). You can now setup your own firebase to avoid this issue.
