### ISSUE TITLE
Migrate to androidx

### ISSUE THREAD

**Issue by michaelbukachi** [droidconKE/droidconKE#9]
I think we should migrate all libraries to androidx

**Comment by wangerekaharun** [comment]
Planning to do so.

**Comment by michaelbukachi** [comment]
If I get some free time. I'll do so and make a pull request

**Comment by wangerekaharun** [comment]
Check out the Kotlin branch, though everything is quite behind, but will
take time to update the braches both kotlin and java so that we can start
accepting the PR's

**Comment by wangerekaharun** [comment]
Migrated to AndroidX

**Comment by michaelbukachi** [comment]
Is the kotlin branch ready for pull requests?

**Comment by wangerekaharun** [comment]
Updating the source code for the kotlin branch by today
